# fly.toml app configuration file generated for vim-with-me on 2024-05-19T09:14:41-06:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'vim-with-me'
primary_region = 'ord'

[build]
  dockerfile = "relay_server.Dockerfile"

[[services]]
  internal_port = 8080
  protocol = "tcp"

  [services.concurrency]
    hard_limit = 10000
    soft_limit = 8000

  [[services.ports]]
    handlers = ["http"]
    port = "80"

  [[services.ports]]
    handlers = ["tls", "http"]
    port = "443"

  [[services.tcp_checks]]
    interval = 10000
    timeout = 2000

[[vm]]
  memory = '16gb'
  cpu_kind = 'performance'
  cpus = 32
