#!/usr/bin/env bash

zig build
for i in {123..135}; do
    echo "TWO: running $1 at round $i"
    rm -f /tmp/td /tmp/td-view-at && LEVEL=error go run ./examples/v2/td/run/main.go --two ai:openai:prompt/THEPRIMEAGEN --one ai:anthropic:prompt/THEPRIMEAGEN --vizFile /tmp/td-view-at --roundTime 7 --seed $i --debug /tmp/td -- ./zig-out/bin/to main.json
done
