#!/usr/bin/env bash

for i in {0..250}; do
    echo "running $1 at round $i"
    LEVEL=error go run ./examples/v2/td/run/main.go --system $1 --seed $i -- ./zig-out/bin/to test.json >> $1_results_strat
done

