#!/usr/bin/env bash

zig build
for i in {27..250}; do
    echo "TWO: running $1 at round $i"
    rm -f /tmp/td2 /tmp/td-viz && LEVEL=error go run ./examples/v2/td/run/main.go --one ai:openai:prompt/THEPRIMEAGEN --two ai:anthropic:prompt/THEPRIMEAGEN --vizFile /tmp/td-view-ab --roundTime 7 --seed $i --debug /tmp/td2 -- ./zig-out/bin/to main.json
done

